// <auto-generated />
using System;
using App.Infra.Db.SqlServer.SqlServerDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Infra.Db.SqlServer.Migrations
{
    [DbContext(typeof(ServiceOnDbContext))]
    [Migration("20250213124037_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Domain.Core.ServiceOn.Address.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.AllService.Entities.AllService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AllService", (string)null);
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.Category.Entities.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MainSerivceId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("MainSerivceId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.Category.Entities.SubCategories", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategoryId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubCategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories", (string)null);
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.FeedBack.Entities.FeedBack", b =>
                {
                    b.Property<int>("FeedBackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedBackId"));

                    b.Property<int>("CostomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedBackId");

                    b.HasIndex("CostomerId");

                    b.HasIndex("ExpertId");

                    b.ToTable("FeedBacks", (string)null);
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.Orders.Entities.CostomerRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("CostomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CostomerId");

                    b.ToTable("CostomerRequest");
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.Orders.Entities.ExpertRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ExpertId");

                    b.ToTable("ExpertRequest");
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.User.Entities.Costomer", b =>
                {
                    b.Property<int>("CostomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostomerId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CostomerId");

                    b.HasIndex("AddressId");

                    b.ToTable("Costomers", (string)null);
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.User.Entities.Expert", b =>
                {
                    b.Property<int>("ExpertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpertId"));

                    b.Property<int>("AbilityId")
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.HasKey("ExpertId");

                    b.HasIndex("AbilityId");

                    b.HasIndex("AddressId");

                    b.ToTable("Experts", (string)null);
                });

            modelBuilder.Entity("CostomerRequestExpert", b =>
                {
                    b.Property<int>("CostomerRequestsId")
                        .HasColumnType("int");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.HasKey("CostomerRequestsId", "ExpertId");

                    b.HasIndex("ExpertId");

                    b.ToTable("CostomerRequestExpert");
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.Category.Entities.Categories", b =>
                {
                    b.HasOne("App.Domain.Core.ServiceOn.AllService.Entities.AllService", "AllService")
                        .WithMany("Categories")
                        .HasForeignKey("MainSerivceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AllService");
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.Category.Entities.SubCategories", b =>
                {
                    b.HasOne("App.Domain.Core.ServiceOn.Category.Entities.Categories", "Categories")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.FeedBack.Entities.FeedBack", b =>
                {
                    b.HasOne("App.Domain.Core.ServiceOn.User.Entities.Costomer", "Costomer")
                        .WithMany("feedBacks")
                        .HasForeignKey("CostomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.ServiceOn.User.Entities.Expert", "Expert")
                        .WithMany("feedBacks")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Costomer");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.Orders.Entities.CostomerRequest", b =>
                {
                    b.HasOne("App.Domain.Core.ServiceOn.Address.Entities.Address", "RequestAdderss")
                        .WithMany("costomerRequests")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.ServiceOn.User.Entities.Costomer", "Costomer")
                        .WithMany("requests")
                        .HasForeignKey("CostomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Costomer");

                    b.Navigation("RequestAdderss");
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.Orders.Entities.ExpertRequest", b =>
                {
                    b.HasOne("App.Domain.Core.ServiceOn.Address.Entities.Address", "RequestAdderss")
                        .WithMany("expertRequests")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.ServiceOn.User.Entities.Expert", "Expert")
                        .WithMany("ExpertRequests")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("RequestAdderss");
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.User.Entities.Costomer", b =>
                {
                    b.HasOne("App.Domain.Core.ServiceOn.Address.Entities.Address", "Address")
                        .WithMany("Costomer")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.User.Entities.Expert", b =>
                {
                    b.HasOne("App.Domain.Core.ServiceOn.Category.Entities.SubCategories", "Abilities")
                        .WithMany("experts")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.ServiceOn.Address.Entities.Address", "Address")
                        .WithMany("Expert")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Abilities");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("CostomerRequestExpert", b =>
                {
                    b.HasOne("App.Domain.Core.ServiceOn.Orders.Entities.CostomerRequest", null)
                        .WithMany()
                        .HasForeignKey("CostomerRequestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.ServiceOn.User.Entities.Expert", null)
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.Address.Entities.Address", b =>
                {
                    b.Navigation("Costomer");

                    b.Navigation("Expert");

                    b.Navigation("costomerRequests");

                    b.Navigation("expertRequests");
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.AllService.Entities.AllService", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.Category.Entities.Categories", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.Category.Entities.SubCategories", b =>
                {
                    b.Navigation("experts");
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.User.Entities.Costomer", b =>
                {
                    b.Navigation("feedBacks");

                    b.Navigation("requests");
                });

            modelBuilder.Entity("App.Domain.Core.ServiceOn.User.Entities.Expert", b =>
                {
                    b.Navigation("ExpertRequests");

                    b.Navigation("feedBacks");
                });
#pragma warning restore 612, 618
        }
    }
}
